package com.example.asteroidradar.database.daos

import androidx.room.*
import androidx.room.OnConflictStrategy.IGNORE
import com.example.asteroidradar.dataClasses.DataClasses
import com.example.asteroidradar.database.Entities.AsteroidsDataTable
import com.example.asteroidradar.database.Entities.CloseApproachDataTable
import com.example.asteroidradar.database.Entities.MasterTable
import timber.log.Timber


@Dao
interface NearEarthAsteroidsDAO {

    @Insert
    fun insertNearEarthAsteroids(asteroidsDataTable: AsteroidsDataTable)

    @Insert(onConflict = IGNORE)
    fun insertCloseApproachInfo(closeApproachDataTable: CloseApproachDataTable)

    @Insert(onConflict = IGNORE)
    fun insertDatesInMasterTable(masterTable: MasterTable)

    @Transaction
    fun insertAsteroidInfo(asteroids: ArrayList<DataClasses.Asteroid>){
        Timber.d("Insert Transaction begun")

        for (asteroid in asteroids) {

            insertDatesInMasterTable(MasterTable(date = asteroid.date))

            val masterTableId = getMasterTableAutoGeneratedDateId(asteroid.date)

            val asteroidDataTable = AsteroidsDataTable(
                id = asteroid.id,
                neoReferenceId = asteroid.neoReferenceId,
                name = asteroid.name,
                nasaJplUrl = asteroid.nasaJplUrl,
                absoluteMagnitude = asteroid.absoluteMagnitudeH,
                isPotentiallyHazardous = asteroid.isPotentiallyHazardousAsteroid,
                isSentryObject = asteroid.isSentryObject,
                selfLink = asteroid.links.self,
                estimatedDiameterFeetMax = asteroid.estimatedDiameter.feet.estimatedDiameterMaximum,
                estimatedDiameterFeetMin = asteroid.estimatedDiameter.feet.estimatedDiameterMinimum,
                estimatedDiameterKiloMetersMax = asteroid.estimatedDiameter.kilometers.estimatedDiameterMaximum,
                estimatedDiameterKiloMetersMin = asteroid.estimatedDiameter.kilometers.estimatedDiameterMinimum,
                estimatedDiameterMetersMax = asteroid.estimatedDiameter.meters.estimatedDiameterMaximum,
                estimatedDiameterMetersMin = asteroid.estimatedDiameter.meters.estimatedDiameterMinimum,
                estimatedDiameterMilesMax = asteroid.estimatedDiameter.miles.estimatedDiameterMaximum,
                estimatedDiameterMilesMin = asteroid.estimatedDiameter.miles.estimatedDiameterMinimum,
                masterId = masterTableId)

         insertNearEarthAsteroids(asteroidDataTable)
            val closeApproachDataTable = CloseApproachDataTable(
                asteroidTableId = asteroid.id,
                closeApproachDate = asteroid.closeApproachData[asteroid.closeApproachData.size-1].closeApproachDate,
                closeApproachDateFull = asteroid.closeApproachData[asteroid.closeApproachData.size-1].closeApproachDateFull,
                epochDateCloseApproach = asteroid.closeApproachData[asteroid.closeApproachData.size-1].epochDateCloseApproach,
                relativeVelocityKmph = asteroid.closeApproachData[asteroid.closeApproachData.size-1].relativeVelocity.kilometersPerHour,
                relativeVelocityMph = asteroid.closeApproachData[asteroid.closeApproachData.size-1].relativeVelocity.milesPerHour,
                relativeVelocityKmps = asteroid.closeApproachData[asteroid.closeApproachData.size-1].relativeVelocity.kilometersPerSecond,
                missDistanceAstronomical = asteroid.closeApproachData[asteroid.closeApproachData.size-1].missDistance.astronomical,
                missDistanceKilometers = asteroid.closeApproachData[asteroid.closeApproachData.size-1].missDistance.kilometers,
                missDistanceLunar = asteroid.closeApproachData[asteroid.closeApproachData.size-1].missDistance.lunar,
                missDistanceMiles = asteroid.closeApproachData[asteroid.closeApproachData.size-1].missDistance.miles,
                closeApproachId = masterTableId)

            insertCloseApproachInfo(closeApproachDataTable)
        }
        Timber.d("Insert Transaction Complete")
    }

    @Query("SELECT master_id FROM Asteroids_MasterTable WHERE date = :date")
     fun getMasterTableAutoGeneratedDateId(date: String): Int

//    @Delete
//    suspend fun deleteAllAsteroidsInfo()
//
//    @Delete
//    suspend fun deleteSpecificDayAsteroidInfo(date: String)

}